"""Corporate DB tool definitions.

Execution is implemented in core as a thin client calling tools-api routes.
"""

TOOLS = {
    "corp_db_search": {
        "enabled": True,
        "name": "corp_db_search",
        "description": (
            "Search internal corporate Postgres database (server-side via tools-api; read-only). "
            "Supports hybrid KB/entity search, exact code lookups, lamp filters, categories, spheres, "
            "portfolio, and mounting compatibility."
        ),
        "source": "builtin",
        "parameters": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string",
                    "description": "Operation kind",
                    "enum": [
                        "hybrid_search",
                        "lamp_exact",
                        "lamp_suggest",
                        "sku_by_code",
                        "application_recommendation",
                        "category_lamps",
                        "portfolio_by_sphere",
                        "portfolio_examples_by_lamp",
                        "sphere_curated_categories",
                        "sphere_categories",
                        "lamp_filters",
                        "category_mountings",
                    ],
                },
                "limit": {"type": "integer", "description": "Max rows (clamped to <=10)", "default": 5},
                "offset": {"type": "integer", "description": "Offset (clamped to <=200)", "default": 0},
                "query": {"type": "string", "description": "Search query for hybrid/entity search and suggestions"},
                "profile": {
                    "type": "string",
                    "description": "Hybrid-search preset profile",
                    "enum": ["kb_search", "kb_route_lookup", "entity_resolver", "candidate_generation", "related_evidence"],
                },
                "knowledge_route_id": {
                    "type": "string",
                    "description": "Optional authoritative KB route id for source-scoped company knowledge lookups.",
                },
                "source_files": {
                    "type": "array",
                    "description": "Explicit KB source-file scope. `knowledge_route_id` takes precedence when both are present.",
                    "items": {"type": "string"},
                },
                "topic_facets": {
                    "type": "array",
                    "description": "Optional route-local topic facets for source-scoped KB ranking and sufficiency.",
                    "items": {"type": "string"},
                },
                "entity_types": {
                    "type": "array",
                    "description": "Optional entity-type override for hybrid search",
                    "items": {"type": "string"},
                },
                "include_debug": {"type": "boolean", "description": "Include hybrid ranking debug info", "default": False},
                "limit_categories": {"type": "integer", "description": "Max category groups in application_recommendation (<=10)", "default": 3},
                "limit_lamps": {"type": "integer", "description": "Max lamp recommendations in application_recommendation (<=10)", "default": 3},
                "limit_portfolio": {"type": "integer", "description": "Max portfolio examples in application_recommendation (<=10)", "default": 2},
                "name": {"type": "string", "description": "Exact lamp name (kind=lamp_exact / portfolio_examples_by_lamp)"},
                "etm": {"type": "string", "description": "ETM code (kind=sku_by_code; provide exactly one of etm/oracl)"},
                "oracl": {"type": "string", "description": "ORACL code (kind=sku_by_code; provide exactly one of etm/oracl)"},
                "category": {
                    "type": "string",
                    "description": "Category name. In kind=category_lamps, exact display-category names may expand to executable leaf categories.",
                },
                "series": {
                    "type": "string",
                    "description": "Canonical business series or broad model family, e.g. LAD LED R500 or NL VEGA.",
                },
                "sphere": {
                    "type": "string",
                    "description": "Sphere name (kind=portfolio_by_sphere / sphere_curated_categories / sphere_categories)",
                },
                "mounting_type": {"type": "string", "description": "Mounting type name/mark or lamp mounting filter"},
                "beam_pattern": {"type": "string", "description": "Beam pattern / light distribution filter, e.g. 30° or Ш"},
                "climate_execution": {"type": "string", "description": "Climate execution filter, e.g. УХЛ1 or УХЛ 4 / 3.1"},
                "electrical_protection_class": {"type": "string", "description": "Electrical protection class filter, e.g. I or II"},
                "explosion_protection_marking": {"type": "string", "description": "Explosion protection marking filter, e.g. 1Ex mb IIС T6 Gb X"},
                "supply_voltage_raw": {"type": "string", "description": "Raw voltage description filter, e.g. 220+40%, 220-30%"},
                "dimensions_raw": {"type": "string", "description": "Dimensions filter, e.g. 774 x 428 x 406 мм"},
                "power_factor_operator": {"type": "string", "description": "Power-factor operator filter, e.g. >="},
                "ip": {"type": "string", "description": "Ingress protection filter, e.g. IP65"},
                "voltage_kind": {"type": "string", "description": "Voltage kind filter", "enum": ["AC", "DC", "AC/DC"]},
                "explosion_protected": {"type": "boolean", "description": "Explosion-protected filter"},
                "power_w_min": {"type": "integer", "description": "Minimum power in watts"},
                "power_w_max": {"type": "integer", "description": "Maximum power in watts"},
                "flux_lm_min": {"type": "integer", "description": "Minimum luminous flux in lumens"},
                "flux_lm_max": {"type": "integer", "description": "Maximum luminous flux in lumens"},
                "cct_k_min": {"type": "integer", "description": "Minimum color temperature in kelvin"},
                "cct_k_max": {"type": "integer", "description": "Maximum color temperature in kelvin"},
                "weight_kg_min": {"type": "number", "description": "Minimum lamp weight in kilograms"},
                "weight_kg_max": {"type": "number", "description": "Maximum lamp weight in kilograms"},
                "cri_ra_min": {"type": "integer", "description": "Minimum color rendering index Ra"},
                "cri_ra_max": {"type": "integer", "description": "Maximum color rendering index Ra"},
                "power_factor_min_min": {"type": "number", "description": "Minimum lower bound for power factor"},
                "power_factor_min_max": {"type": "number", "description": "Maximum lower bound for power factor"},
                "temp_c_min": {"type": "integer", "description": "Minimum operating temperature overlap"},
                "temp_c_max": {"type": "integer", "description": "Maximum operating temperature overlap"},
                "voltage_nominal_v_min": {"type": "integer", "description": "Minimum nominal voltage in volts"},
                "voltage_nominal_v_max": {"type": "integer", "description": "Maximum nominal voltage in volts"},
                "voltage_min_v_min": {"type": "integer", "description": "Minimum allowed lower voltage bound in volts"},
                "voltage_min_v_max": {"type": "integer", "description": "Maximum allowed lower voltage bound in volts"},
                "voltage_max_v_min": {"type": "integer", "description": "Minimum allowed upper voltage bound in volts"},
                "voltage_max_v_max": {"type": "integer", "description": "Maximum allowed upper voltage bound in volts"},
                "voltage_tol_minus_pct_min": {"type": "number", "description": "Minimum negative voltage tolerance in percent"},
                "voltage_tol_minus_pct_max": {"type": "number", "description": "Maximum negative voltage tolerance in percent"},
                "voltage_tol_plus_pct_min": {"type": "number", "description": "Minimum positive voltage tolerance in percent"},
                "voltage_tol_plus_pct_max": {"type": "number", "description": "Maximum positive voltage tolerance in percent"},
                "length_mm_min": {"type": "number", "description": "Minimum lamp length in millimeters"},
                "length_mm_max": {"type": "number", "description": "Maximum lamp length in millimeters"},
                "width_mm_min": {"type": "number", "description": "Minimum lamp width in millimeters"},
                "width_mm_max": {"type": "number", "description": "Maximum lamp width in millimeters"},
                "height_mm_min": {"type": "number", "description": "Minimum lamp height in millimeters"},
                "height_mm_max": {"type": "number", "description": "Maximum lamp height in millimeters"},
                "warranty_years_min": {"type": "integer", "description": "Minimum warranty in years"},
                "warranty_years_max": {"type": "integer", "description": "Maximum warranty in years"},
                "fuzzy": {"type": "boolean", "description": "Use FTS fallback when supported", "default": False},
            },
            "required": ["kind"],
        },
    }
}
